name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # All shell steps will run inside nextword_site/
    defaults:
      run:
        working-directory: nextword_site

    env:
      DJANGO_SETTINGS_MODULE: nextword_site.settings
      SECRET_KEY: test
      DEBUG: "false"
      TF_CPP_MIN_LOG_LEVEL: "2"  # quiet TensorFlow logs (if imported)

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('nextword_site/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps
        run: sudo apt-get update

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        run: python manage.py check --deploy --fail-level WARNING || true

      - name: Run tests
        run: pytest -q
