name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      DJANGO_SETTINGS_MODULE: nextword_site.settings
      SECRET_KEY: test
      DEBUG: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install system deps
        run: sudo apt-get update

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r nextword_site/requirements.txt

      - name: Django checks
        working-directory: nextword_site
        run: python manage.py check --deploy --fail-level WARNING || true

      - name: Run tests
        working-directory: nextword_site
        run: pytest -q

  dependabot-automerge:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta

      - name: Auto-merge security or patch updates
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          UPDATE_TYPE: ${{ steps.meta.outputs.update-type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Dependabot update type: ${UPDATE_TYPE}"
          if [[ "${UPDATE_TYPE}" == "security" || "${UPDATE_TYPE}" == "version-update:semver-patch" ]]; then
            echo "Enabling auto-merge (squash)…"
            gh pr merge --auto --squash "${PR_URL}"
          else
            echo "Not auto-merging update type: ${UPDATE_TYPE}"
          fi
