name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      DJANGO_SETTINGS_MODULE: nextword_site.settings
      SECRET_KEY: test
      DEBUG: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install system deps
        run: sudo apt-get update

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r nextword_site/requirements.txt

      - name: Django checks
        working-directory: nextword_site
        run: python manage.py check --deploy --fail-level WARNING || true

      - name: Run tests
        working-directory: nextword_site
        run: pytest -q
